# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          download_url="https://corretto.aws/downloads/latest/amazon-corretto-11-x64-linux-jdk.tar.gz"
          wget -O $RUNNER_TEMP/java_package.tar.gz $download_url
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'jdkfile'
          jdkFile: ${{ runner.temp }}/java_package.tar.gz
          java-version: '11.0.0'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Check with Gradle
        run: ./gradlew yarn_install yarn_build check
      - name: Build with Gradle and generate artifacts
        run: ./gradlew yarn_install yarn_build assemble
      - name: Upload artifacts  # Find artifacts under actions/jobs
        uses: actions/upload-artifact@v2
        with:
          name: jetbrains-zenuml
          path: ./build/distributions/zenuml.zip
